version: "3"

services:
  postgres:
    image: "postgres:latest"
    environment:
      POSTGRES_USER: "carto"
      POSTGRES_PASSWORD: "carto_pwd"
      POSTGRES_DB: "carto_db"
    volumes:
      - "./data/postgres:/var/lib/postgresql/data"
    ports:
      - "5432:5432"

  pgadmin:
    image: "dpage/pgadmin4:latest"
    environment:
      PGADMIN_DEFAULT_EMAIL: "pgadmin"
      PGADMIN_DEFAULT_PASSWORD: "pgadmin"
    #volumes:
    #  - "./data/pgadmin:/var/lib/pgadmin"
    # commenter volumes... avec linux
    ports:
      - "8080:80"